import { IconType } from "react-icons";

import {
  HiArrowUpRight,
  HiOutlineLink,
  HiArrowTopRightOnSquare,
  HiEnvelope,
  HiCalendarDays,
  HiArrowRight,
  HiOutlineEye,
  HiOutlineEyeSlash,
  HiOutlineDocument,
  HiOutlineGlobeEuropeAfrica,
  HiOutlineRocketLaunch,
} from "react-icons/hi2";

import {
  PiHouseDuotone,
  PiUserCircleDuotone,
  PiGridFourDuotone,
  PiBookBookmarkDuotone,
  PiImageDuotone,
} from "react-icons/pi";

import {
  SiJavascript,
  SiNextdotjs,
  SiFigma,
  SiSupabase,
  SiPostgresql,
  SiGit,
  SiDocker,
  SiExpress,
  SiNodedotjs,
  SiMongodb,
  SiHtml5,
  SiCss,
  SiTypescript,
  SiKubernetes,
  SiPostman,
  SiVercel,
  SiNetlify,
  SiRender,
} from "react-icons/si";

import { VscVscode } from "react-icons/vsc";

import {
  FaDiscord,
  FaGithub,
  FaLinkedin,
  FaX,
  FaThreads,
  FaInstagram,
  FaXTwitter,
  FaFacebook,
  FaPinterest,
  FaWhatsapp,
  FaReddit,
  FaTelegram,
  FaReact,
  FaAws,
} from "react-icons/fa6";

export const iconLibrary: Record<string, IconType> = {
  arrowUpRight: HiArrowUpRight,
  aws: FaAws,
  vercel: SiVercel,
  netlify: SiNetlify,
  render: SiRender,
  html: SiHtml5,
  vscode: VscVscode,
  css: SiCss,
  expressjs: SiExpress,
  postgresql: SiPostgresql,
  typescript: SiTypescript,
  kubernetes: SiKubernetes,
  postman: SiPostman,
  nodejs: SiNodedotjs,
  mongodb: SiMongodb,
  git: SiGit,
  docker: SiDocker,
  arrowRight: HiArrowRight,
  email: HiEnvelope,
  globe: HiOutlineGlobeEuropeAfrica,
  person: PiUserCircleDuotone,
  grid: PiGridFourDuotone,
  book: PiBookBookmarkDuotone,
  openLink: HiOutlineLink,
  calendar: HiCalendarDays,
  home: PiHouseDuotone,
  gallery: PiImageDuotone,
  discord: FaDiscord,
  eye: HiOutlineEye,
  react: FaReact,
  eyeOff: HiOutlineEyeSlash,
  github: FaGithub,
  linkedin: FaLinkedin,
  x: FaX,
  twitter: FaXTwitter,
  threads: FaThreads,
  arrowUpRightFromSquare: HiArrowTopRightOnSquare,
  document: HiOutlineDocument,
  rocket: HiOutlineRocketLaunch,
  javascript: SiJavascript,
  nextjs: SiNextdotjs,
  supabase: SiSupabase,
  figma: SiFigma,
  facebook: FaFacebook,
  pinterest: FaPinterest,
  whatsapp: FaWhatsapp,
  reddit: FaReddit,
  telegram: FaTelegram,
  instagram: FaInstagram,
};

export type IconLibrary = typeof iconLibrary;
export type IconName = keyof IconLibrary;
